# Proje bilgileri
sonar.projectKey=image_forgery_detection
sonar.projectName=Image Forgery Detection System
sonar.projectVersion=1.0

# SonarQube sunucusu
sonar.host.url=http://localhost:9000

# Taranacak kaynak kodlar?n konumu
sonar.sources=.

# Python sürümü
sonar.python.version=3.12

# Analiz d??? b?rak?lacak klasörler
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/forgery-ui/**,**/docs/**

# Kodun yaz?ld??? dil ve karakter seti
sonar.language=py
sonar.sourceEncoding=UTF-8